config/routes.rb
Overflow::Application.routes.draw do
  root :to => "application#index"
  resources :users, except:[:index]
  resource :session
  
  resources :questions do
    resources :votes
     resources :answers
  end
    # resources :answers
  match "/answers/:id/edit" => "answers#edit" , :as => :edit_answer
  match "/answers/:id" => "answers#update" 
  # match "/answers" => "answers#create"
  # match "/answers/:answer_id/edit" =>"answers#edit"
  # match "/answers/:answer_id" =>"answers#update"

  #post "/questions/:id/votes" => "votes#create", :as => :vote_up_question
  resources :responses
  match "/:respondable_type/:id/responses/new" => "responses#new"
  resources :votes
  match "/:id/votes/upvotes" => "votes#upvotes"
  match "/:id/votes/downvotes" => "votes#downvotes"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :responses, :as => :respondable
  has_many :votes, :as => :voteable
  attr_accessible :question_id,:content
  validates :content, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :content
  has_many :votes, :as => :voteable
  belongs_to :user
  has_many :answers
  has_many :responses, :as => :respondable
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :respondable, :polymorphic => true
  attr_accessible :content
  has_many :votes, :as => :voteable
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt
  attr_accessible :email, :name, :password, :password_confirmation
  validates :name, :presence => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  has_secure_password
  has_many :questions
  has_many :responses
  has_many :answers
  has_many :votes
  validates_confirmation_of :password
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, :polymorphic => true
  belongs_to :user
  attr_accessible :number
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @answer = Answer.new 
  end

  def show
    @question = Question.find(params[:id])
    
  end

  def create
    @answer = Answer.create(:content => params[:answer][:content])
    @question = Question.find(params[:answer][:question_id])
    @user = User.find(session[:current_user_id])
    @question.answers << @answer
    @user.answers << @answer
    redirect_to root_path
  end

  def update
    @answer =Answer.find(params[:id])
    @answer.update_attributes(params[:answer])
    @question = Question.find(@answer.question_id)
    @answers = @question.answers
    redirect_to "/questions/#{@question.id}"
  end

  def edit
    @answer= Answer.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def login!(user)
    session[:current_user_id] = user.id
  end

  def logout!
    session.delete(:current_user_id)
  end

  def current_user
    @current_user ||= User.find_by_id(session[:current_user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  def create
    # current_user = User.find(session[:current_user_id])
    @question = current_user.questions.build(params[:question])
    if @question.save
      flash[:notice] = 'Your question was created successfully'
      redirect_to questions_path # => '/questions'
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(params[:question])
      redirect_to @question
    else
      render 'edit'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def new
    @type = params[:respondable_type]
    @responding_to_obj = eval(params[:respondable_type].capitalize).find(params[:id])

    # if @type == "question"
    #   @responding_to_obj = Question.find(params[:id])
    # else 
    #   @responding_to_obj = Answer.find(params[:id])
    # end
  end

  def show
    @question = Question.find(params[:id])  
  end

  def create
    @user = User.find(session[:current_user_id])
    @responding_to_obj = eval(params[:response][:respondable_type]).find(params[:response][:respondable_id])
    @response = Response.create(content: params[:response][:content])
    @responding_to_obj.responses << @response
    @user.responses << @response
    if params[:response][:respondable_type] == "Question"
      @question_id = @response.respondable.id
    else
      @question_id = @response.respondable.question_id
    end
    @answers = @responding_to_obj.answers if @responding_to_obj.class.to_s == 'Question'
    redirect_to "/questions/#{@question_id}"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user_session = User.new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:current_user_id] = @user.id
      redirect_to '/users/show'
    else 
      flash[:notice] = "Invalid email and password"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @questions = Question.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @users = User.all 
      render :show
    else 
      render :new
    end
  end

  def show
    @users = User.all
    render :show
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def upvotes  
     changevotes(params[:class],1) 
 end

def downvotes
     changevotes(params[:class],-1)
end

private
def changevotes(type,howmuch)
      @typeClass = Kernel.const_get(type)
      user =User.find(session[:current_user_id])
      @type = @typeClass.find(params[:id])
      @question = Question.find(params[:question_id])
      if @type.votes.size == 0# if the question has no votes
       @vote = Vote.create(:number=>1)
       @vote.user = user
       @type.votes << @vote
       redirect_to question_path(@question)
     elsif @type.votes.first.number == 1
      redirect_to question_path(@question) 
    else 
      @votes_number = @type.votes.first.number
      @type.votes.first.update_attributes(:number=>@votes_number+howmuch)
      @vote = @type.votes.first
      user.votes << @vote
      redirect_to question_path(@question)
    end 
  end
end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/edit.html.erb
<%= form_for :answer, :url =>{:action=> "update"} do |f|%>
<%= f.label :content%><br>
<%= f.text_area :content, value: @answer.content %><br>
<%= f.submit :submit %>
<% end %>

app/views/answers/new.html.erb
<h2>Answer</h2>
<%=form_for @answer do |f|%>
<%=f.label :content %><br>
<%=f.text_area :content  %><br>
<%= f.hidden_field :question_id, value: params[:question_id].to_i%>
<%=f.submit :submit  %>
<% end %>

app/views/application/index.html.erb
<h1>DBC OVERFLOW!</h1>



<h2>Question</h2>
<%=link_to "Add Question" , new_question_path if logged_in? %>
<br><br>

<%= render :partial => 'questions/questions' %>

app/views/layouts/_header.html.erb
<%=link_to "Home", root_path %>
<%=link_to "SignUp", new_user_path %>
<%=link_to "Login", new_session_path unless logged_in?%>
<%=link_to "Logout", {controller: 'sessions', action: 'destroy'}, :method => :delete if logged_in?%>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Overflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'layouts/header'%><br><br>
<%= yield %>

</body>
</html>

app/views/questions/_questions.html.erb
<%@questions = Question.all%>
<% if @questions %>
<%@questions.each do |question|%>
<hr>
<b><%= link_to question.title, question_path(question.id)%></b><br>
<%=question.content%>

<br><br>
<%end%>
<%end%>

app/views/questions/edit.html.erb
<%= form_for :question, :url => { :action => "update" }, :html => {:method => "put"} do |f|%>
<%= f.label :title%><br>
<%=f.text_field :title, value: @question.title%>
<br>
<%= f.label :content%><br>
<%=f.text_area :content, value: @question.content %><br>
<%=f.submit :submit %>
<%end%>

app/views/questions/index.html.erb
<%= render :partial =>'questions' %>

app/views/questions/new.html.erb
<%= form_for :question, url: {:action =>"create"} do |f| %>
Title<br><%= f.text_field :title %><br>
Content<br><%= f.text_area :content %><br>
<%= f.submit "Submit question" %>
<% end %>

app/views/questions/show.html.erb
<br>
<h2><%= @question.title%></h2>
<p><%= @question.content %></p>
<%if @question.votes.size !=0 %>
<p><%=@question.votes.first.number %> votes </p>
<%end%>
<%= link_to "+", "/#{@question.id}/votes/upvotes?class=#{@question.class}&question_id=#{@question.id}" if logged_in?%>
<%= link_to "-", "/#{@question.id}/votes/downvotes?class=#{@question.class}&question_id=#{@question.id}" if logged_in?%>
<%=link_to "Respond", "/question/#{@question.id}" + new_response_path if logged_in?%>

<h3>Responses to </h3>
<% @question.responses.each do |response| %>
<hr>
<p><%= response.content %> by <%=@question.user.name%></p>
<%if response.votes.size !=0 %>
<p><%=response.votes.first.number %></p>
<%end%>
<%= link_to "+", "/#{response.id}/votes/upvotes?class=#{response.class}&question_id=#{@question.id}" if logged_in?%>
<%= link_to "-", "/#{response.id}/votes/downvotes?class=#{response.class}&question_id=#{@question.id}" if logged_in?%>
<% end %>


<%= link_to "Edit Question", edit_question_path(@question) if logged_in?%><br><br>


<h2><u>Answers</u></h2>
<% if @answers %>
<%@answers.each do |answer| %>
<hr>
<%= answer.content%> by <%=answer.user.name%> <br>
<%=link_to "Edit Answer", edit_answer_path(answer) if logged_in?%><br>
<hr>
<%if answer.votes.size !=0 %>
<p><%=answer.votes.first.number %></p>
<%end%>
<%= link_to "+", "/#{answer.id}/votes/upvotes?class=#{answer.class}&question_id=#{@question.id}" if logged_in?%>
<%= link_to "-", "/#{answer.id}/votes/downvotes?class=#{answer.class}&question_id=#{@question.id}" if logged_in?%>
<%answer.responses.each do |response|%>
<%=response.content%> by <%=response.user.name%><br>
<%= link_to "+", "/#{response.id}/votes/upvotes?class=#{response.class}&question_id=#{@question.id}" if logged_in?%>
<%= link_to "-", "/#{response.id}/votes/downvotes?class=#{response.class}&question_id=#{@question.id}" if logged_in?%>
<%end%>
<%= link_to "Respond", "/answer/#{answer.id}" + new_response_path if logged_in?%>
<%end%>
<%end%>
<br>
<%= link_to "Add Answer", new_question_answer_path(@question) if logged_in? %>

app/views/questions/update.html.erb
<%= form_for :question, url: {:action =>"update"} do |f| %>
<%= f.text_field :title %>
<%= f.text_area :content %>
<%= f.submit "Submit question" %>
<% end %>

app/views/responses/new.html.erb
<% if @responding_to_obj.class == "Question" %> 
<h3>Response for "<%=@responding_to_obj.title%>":</h3>
<% end %>
<p><%= @responding_to_obj.content %></p>
<%= form_for :response, url: {action: 'create'} do |f| %>
Response<br><%= f.text_area :content %><br>
<%= f.hidden_field :respondable_id, :value => @responding_to_obj.id  %>
<%= f.hidden_field :respondable_type, :value => @responding_to_obj.class %>
<%= f.submit "Submit response" %>
<% end %>

app/views/users/login.html.erb
<%=form_for @user ,:url =>{:action =>"login"} do |f|%>
<%=f.text_field :email%>
<%=f.text_field :password%>
<%=f.submit "Submit"%>
<%end%>

app/views/users/new.html.erb
<%= form_for :user, :url =>{:action =>"create"} do |f|%>
Name:
<%= f.text_field :name %>
Email:
<%= f.text_field :email %>
Password
<%= f.text_field :password %>
Password Confirmation
<%= f.text_field :password_confirmation %>
<%=f.submit "Submit"%>
<%end%>

app/views/users/show.html.erb
<h2>Users</h2>
<% @users.each do |x| %>
<%= x.name %><br>
<% end %>